DeckOfCards/DeckOfCards/Models/Card.cs
namespace DeckOfCards.Models
{
    public class Card
    {
        public string code { get; set; }
        public string image { get; set; }
        public Images images { get; set; }
        public string value { get; set; }
        public string suit { get; set; }
    }
}

DeckOfCards/DeckOfCards/Models/Deck.cs
namespace DeckOfCards.Models
{
    public class Deck
    {
        public string deck_id { get; set; }
    }
}

DeckOfCards/DeckOfCards/Models/ErrorViewModel.cs
namespace DeckOfCards.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DeckOfCards/DeckOfCards/Models/Images.cs
namespace DeckOfCards.Models
{
    public class Images
    {
        public string svg { get; set; }
        public string png { get; set; }
    }
}

DeckOfCards/DeckOfCards/Models/RootObject.cs
namespace DeckOfCards.Models
{
    public class RootObject
    {
        public bool success { get; set; }
        public string deck_id { get; set; }
        public List<Card> cards { get; set; }
        public int remaining { get; set; }
    }
}

DeckOfCards/DeckOfCards/Controllers/DeckOfCardsController.cs
using DeckOfCards.Models;
using Flurl.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Windows;
using static System.Net.WebRequestMethods;

namespace DeckOfCards.Controllers
{

    public class DeckOfCardsController : Controller
    {
        public IActionResult Index()
        {
            string apiUri = "https://www.deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1";
            var apiTask = apiUri.GetJsonAsync<RootObject>();
            apiTask.Wait();
            RootObject result = apiTask.Result;
            return View(result);

        }

        public IActionResult List(string deckId)
        {
            string deckOfCardsApi = "https://www.deckofcardsapi.com/api/deck/" + deckId + "/draw/?count=5";
            var apiUri = deckOfCardsApi;
            var apiTask = apiUri.GetJsonAsync<RootObject>();
            apiTask.Wait();
            RootObject result = apiTask.Result;
            //List<Card> newHand = result.cards.ToList();

            return View(result.cards);
        }

    }


}

DeckOfCards/DeckOfCards/Controllers/HomeController.cs
using DeckOfCards.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DeckOfCards.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DeckOfCards/DeckOfCards/Views/DeckOfCards/Index.cshtml
@model DeckOfCards.Models.RootObject

@{
    ViewData["Title"] = "ViewDeckId";
}

<h1>ViewDeckId</h1>

<div>
    <h4>RootObject</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.success)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.success)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.deck_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.deck_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.remaining)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.remaining)
        </dd>
    </dl>
</div>

@Html.ActionLink("Draw 5", "List", new { deckId = Model.deck_id })

DeckOfCards/DeckOfCards/Views/DeckOfCards/List.cshtml
@model IEnumerable<DeckOfCards.Models.Card>

@{
    ViewData["Title"] = "List";
}

<h1>Draw 5</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.suit)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.suit)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

DeckOfCards/DeckOfCards/Views/DeckOfCards/sample.cshtml
@model IEnumerable<DeckOfCards.Models.RootObject>

@{
    ViewData["Title"] = "sample";
}

<h1>sample</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.success)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.deck_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.remaining)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.success)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.deck_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.remaining)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

DeckOfCards/DeckOfCards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeckOfCards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DeckOfCards.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeckOfCards</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DeckOfCards" asp-action="Index">Deck of Cards</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DeckOfCards - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>