ConsumingAPIs/ConsumingAPIs/Models/ClassApi.cs
namespace ConsumingAPIs.Models
{
    public class ClassApi
    {
        public string? index { get; set; }
        public string? name { get; set; }
        public string? url { get; set; }

    }
}

ConsumingAPIs/ConsumingAPIs/Models/ClassDetailsApi.cs
namespace ConsumingAPIs.Models
{
    public class ClassDetailsApi
    {
        public string index { get; set; }
        public string name { get; set; }
        public int hit_die { get; set; }
        public List<ClassInventoryApi> starting_equipment { get; set; }
        public string url { get; set; }

    }
}

ConsumingAPIs/ConsumingAPIs/Models/ClassEquipmentApi.cs
namespace ConsumingAPIs.Models
{
    public class ClassEquipmentApi
    {
        public string index { get; set; }
        public string name { get; set; }
        public string url { get; set; }
    }

}

ConsumingAPIs/ConsumingAPIs/Models/ClassInventoryApi.cs
namespace ConsumingAPIs.Models
{
    public class ClassInventoryApi
    {
        public ClassEquipmentApi equipment { get; set; }
        public int quantity { get; set; }

    }
}

ConsumingAPIs/ConsumingAPIs/Models/ClassListApi.cs
namespace ConsumingAPIs.Models
{
    public class ClassListApi
    {
        public int count { get; set; }
        public List<ClassApi> results { get; set; }
    }
}

ConsumingAPIs/ConsumingAPIs/Models/ErrorViewModel.cs
namespace ConsumingAPIs.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConsumingAPIs/ConsumingAPIs/Models/FishApi.cs
namespace ConsumingAPIs.Models
{
    public class FishApi
    {
        public int id { get; set; }
        public string name { get; set; }   
        public string url { get; set; }
        public FishMetaApi  meta { get; set; }

    }
}

ConsumingAPIs/ConsumingAPIs/Models/FishClassificationApi.cs
namespace ConsumingAPIs.Models
{
    public class FishClassificationApi
    {
        public string kingdom { get; set; }

        public string phylum { get; set; }

        public string order { get; set; }

        public string family { get; set; }

        public string genus { get; set; }

        public string species { get; set; }






    }
}

ConsumingAPIs/ConsumingAPIs/Models/FishMetaApi.cs
namespace ConsumingAPIs.Models
{
    public class FishMetaApi
    {
        public string conservation_status { get; set; }
        public FishClassificationApi scientific_classification { get; set; }

        public string binomial_name { get; set; }  
    }
}

ConsumingAPIs/ConsumingAPIs/Models/MovieApi.cs
namespace ConsumingAPIs.Models
{
    public class MovieApi
    {
        public int rank { get; set; }
        public string title { get; set; }
        public string thumbnail { get; set; }
        public string rating { get; set; }
        public string id { get; set; }
        public int year { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string trailer { get; set; }
        public List<string> genre { get; set; }
        public List<string> director { get; set; }
        public List<string> writers { get; set; }
        public string imdbid { get; set; }

    }
}

ConsumingAPIs/ConsumingAPIs/Controllers/DndController.cs
using Microsoft.AspNetCore.Mvc;
using ConsumingAPIs.Models;
using Flurl.Http;

namespace ConsumingAPIs.Controllers
{
    public class DndController : Controller
    {
        public IActionResult Index()
        {
            string apiUri = "https://www.dnd5eapi.co/api/classes";
            var apiTask = apiUri.GetJsonAsync<ClassListApi>();
            apiTask.Wait();
            ClassListApi result = apiTask.Result;
            return View(result.results);

        }
        public ActionResult ClassDetails(string index)
        {
            string apiUri = $"https://www.dnd5eapi.co/api/classes/{index}";
            var apiTask = apiUri.GetJsonAsync<ClassDetailsApi>();
            apiTask.Wait();
            ClassDetailsApi result = apiTask.Result;
            return View(result);
        }
    }
}

ConsumingAPIs/ConsumingAPIs/Controllers/FishController.cs
using Microsoft.AspNetCore.Mvc;
using Flurl;
using ConsumingAPIs;
using ConsumingAPIs.Models;
using Flurl.Http;

namespace ConsumingAPIs.Controllers
{
    public class FishController : Controller
    {
        // GET: FishController
        public ActionResult Index()
        {
            var apiUri = "https://fish-species.p.rapidapi.com/fish_api/fishes";
            var apiTask = apiUri.WithHeaders(new
            {
                x_rapidapi_host = "fish-species.p.rapidapi.com",
                x_rapidapi_key = "8100deed49msh72cb0917eb05701p1a969cjsn1e1525ec8735"

            }).GetJsonAsync<List<FishApi>>();
            apiTask.Wait();
            List<FishApi> fishes = apiTask.Result;
            return View(fishes);
        }

        // GET: FishController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FishController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FishController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FishController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FishController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FishController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FishController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ConsumingAPIs/ConsumingAPIs/Controllers/HomeController.cs
using ConsumingAPIs.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConsumingAPIs.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConsumingAPIs/ConsumingAPIs/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using ConsumingAPIs.Models;
using Flurl.Http;

namespace ConsumingAPIs.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            string apiUri = "https://imdb-top-100-movies.p.rapidapi.com/";
            var apiTask = apiUri.WithHeaders(new
            {
                x_rapidapi_host = "imdb-top-100-movies.p.rapidapi.com",
                x_rapidapi_key = "8100deed49msh72cb0917eb05701p1a969cjsn1e1525ec8735"

            }).GetJsonAsync<List<MovieApi>>();
            apiTask.Wait();
            List<MovieApi> movies = apiTask.Result;
            return View(movies);

        }

        public ActionResult Details(string id)
        {
            string apiUri = $"https://imdb-top-100-movies.p.rapidapi.com/{id}";
            var apiTask = apiUri.WithHeaders(new
            {
                x_rapidapi_host = "imdb-top-100-movies.p.rapidapi.com",
                x_rapidapi_key = "8100deed49msh72cb0917eb05701p1a969cjsn1e1525ec8735"

            }).GetJsonAsync<MovieApi>();
            apiTask.Wait();
            MovieApi movie = apiTask.Result;
            return View(movie);
        }


    }
}

ConsumingAPIs/ConsumingAPIs/Views/Fish/Index.cshtml
@model IEnumerable<ConsumingAPIs.Models.FishApi>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.url)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.url)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

ConsumingAPIs/ConsumingAPIs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConsumingAPIs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConsumingAPIs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ConsumingAPIs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movie List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dnd" asp-action="Index">DnD Stuffs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendarific" asp-action="Index">Cal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ConsumingAPIs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>